// Running total of the Claude tokens used to build this app, one entry per git version.
// Generated by tools/token_usage.py --record. Don't edit by hand.
window.BUILD_LOG = [
  {
    "version": 1,
    "date": "2026-10-08",
    "label": "First version in Git: Start, four levels, Ethics, Lab report",
    "model": "Claude Opus 5.5",
    "responses": 140,
    "tokens": {
      "input": 280,
      "output": 192024,
      "cacheWrite": 952570,
      "cacheRead": 26811574
    }
  },
  {
    "version": 2,
    "date": "2026-10-08",
    "label": "Tone pass, linked sources, How this app was made tab, alternative assignment",
    "model": "Claude Opus 5.5",
    "responses": 179,
    "tokens": {
      "input": 358,
      "output": 243642,
      "cacheWrite": 1400474,
      "cacheRead": 43076783
    }
  },
  {
    "version": 3,
    "date": "2026-10-08",
    "label": "Landing page is How this app was made; open-ended alternative assignment",
    "model": "Claude Opus 5.5",
    "responses": 191,
    "tokens": {
      "input": 382,
      "output": 259203,
      "cacheWrite": 1423063,
      "cacheRead": 49022056
    }
  },
  {
    "version": 4,
    "date": "2026-10-08",
    "label": "Token total only, Mr. Hotchkiss, GitHub Pages setup",
    "model": "Claude Opus 5.5",
    "responses": 199,
    "tokens": {
      "input": 398,
      "output": 266079,
      "cacheWrite": 1434961,
      "cacheRead": 53148971
    }
  },
  {
    "version": 5,
    "date": "2026-10-08",
    "label": "Link to the alternative assignment",
    "model": "Claude Opus 5.5",
    "responses": 210,
    "tokens": {
      "input": 420,
      "output": 271124,
      "cacheWrite": 1442198,
      "cacheRead": 58919980
    }
  }
];
