"""Total the Claude tokens used to build this app and record them in app/build-log.js.

Claude Code keeps a log of every conversation in ~/.claude/projects/<project>/<session>.jsonl.
Each response Claude sends carries a usage record: input tokens, output tokens, and
tokens written to or read from the prompt cache. This script adds them up.

Usage:
  python tools/token_usage.py                          # print totals so far
  python tools/token_usage.py --until 2026-10-08T04:23:33Z
  python tools/token_usage.py --record "What changed"   # append an entry before a commit

Run with --record just before each git commit, then commit app/build-log.js along with
the other changes, so every version of the app carries the running total.
"""
import argparse, datetime, glob, json, os, pathlib, re

ROOT = pathlib.Path(__file__).resolve().parent.parent
LOG_JS = ROOT / "app" / "build-log.js"
# Claude Code names the project folder after the project path, with separators replaced by dashes
PROJECT_DIR = pathlib.Path.home() / ".claude" / "projects" / re.sub(r"[^A-Za-z0-9]", "-", str(ROOT))


def parse_time(s):
    return datetime.datetime.fromisoformat(s.replace("Z", "+00:00"))


def totals(until=None):
    seen, tok = set(), {"input": 0, "output": 0, "cacheWrite": 0, "cacheRead": 0}
    for path in glob.glob(str(PROJECT_DIR / "*.jsonl")):
        with open(path, encoding="utf-8") as f:
            for line in f:
                try:
                    e = json.loads(line)
                except json.JSONDecodeError:
                    continue
                ts = e.get("timestamp")
                if not ts or (until and parse_time(ts) > until):
                    continue
                if e.get("type") != "assistant":
                    continue
                m = e.get("message", {})
                u = m.get("usage")
                key = (m.get("id"), e.get("requestId"))
                if not u or key in seen:  # one response can be logged as several entries
                    continue
                seen.add(key)
                tok["input"] += u.get("input_tokens") or 0
                tok["output"] += u.get("output_tokens") or 0
                tok["cacheWrite"] += u.get("cache_creation_input_tokens") or 0
                tok["cacheRead"] += u.get("cache_read_input_tokens") or 0
    return tok, len(seen)


def read_log():
    if not LOG_JS.exists():
        return []
    text = LOG_JS.read_text(encoding="utf-8")
    return json.loads(text[text.index("["): text.rindex("]") + 1])


def write_log(entries):
    body = json.dumps(entries, indent=2)
    LOG_JS.write_text(
        "// Running total of the Claude tokens used to build this app, one entry per git version.\n"
        "// Generated by tools/token_usage.py --record. Don't edit by hand.\n"
        f"window.BUILD_LOG = {body};\n", encoding="utf-8")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--until", help="only count usage up to this ISO time")
    ap.add_argument("--record", metavar="LABEL", help="append an entry to app/build-log.js")
    ap.add_argument("--date", help="date to show for the entry (defaults to --until or today)")
    a = ap.parse_args()
    until = parse_time(a.until) if a.until else None
    tok, responses = totals(until)
    print(f"{responses} responses, {sum(tok.values()):,} tokens")
    for k, v in tok.items():
        print(f"  {k:10} {v:>14,}")
    if a.record:
        entries = read_log()
        when = (until or datetime.datetime.now().astimezone()).date().isoformat()
        entries.append({"version": len(entries) + 1, "date": a.date or when, "label": a.record,
                        "model": "Claude Opus 5.5", "responses": responses, "tokens": tok})
        write_log(entries)
        print(f"Recorded version {len(entries)} in {LOG_JS.relative_to(ROOT)}")
